### PR TITLE
IsVisible ugh

### PR DESCRIPTION
**Pull request by cantbeatme**
Anyone got a clue to what's wrong with the traceray shit?
I think that's what's up with the Awall, at least what I've traced it down to.
Help??

### CODE REVIEW

**Comment by certmemer** [comment]
What do you mean exactly?

**Comment by cantbeatme** [comment]
Found someone with a similar problem @ UC: https://gfycat.com/ElderlyUnfinishedHoneybee

The top right most column is his result to autowall damage, it's at 0 for certain people, and their names don't appear either. Can't seem to track it down.

**Comment by certmemer** [comment]
Are you calling tracetoexit from memory or using esoterik's rebuilt one? Can't think of anything else.

**Comment by cantbeatme** [comment]
esoterik's source, but heavy modifications trying to hunt down the issue. It was working perfectly like 2 months ago, but then some update came out and the names stopped showing up & A-wall just couldn't read em.

**Comment by certmemer** [comment]
Calling from memory and never had a single problem. Do you have a paste so you can check if it's still an issue?

**Comment by cantbeatme** [comment]
nop, completely removed it #manualfire 2k17, a half working autowall isn't very trustworthy xD

**Pull request merged**
