### PR TITLE
dLights - Read

### PR DESCRIPTION
**Pull request by cantbeatme**
Adds dLights

### CODE REVIEW

**Comment by certmemer** [comment]
You could at least use the proper naming, you know.

**Comment by cantbeatme** [comment]
I could of uploaded the visual studio project information so the new file would show up in the solution explorer too.

But see, I didn't, so now you can rename it, then drag it in, and edit the single line for the header import.

**Comment by certmemer** [comment]
I get it, but it's a pull request, you just don't do that shit. It looks out of place and is incomplete.

**Comment by noylon2k** [comment]
How can i remove the Virus in the Hack ?
when i compile it , theres a Virus in it.
When i try to boot my PC only a screen with "TeamGamerfood .." is shown 👎 
But the hack itself is working thanks for that

**Comment by certmemer** [comment]
owned

**Comment by noylon2k** [comment]
No, I used a old computer with no programms n stuff but still asking how i could fix that.
Reinstall Windows and my PC was fine again.
I'm new to programming and young, even my english skills aren't that .. you know.

**Comment by A5-** [comment]
Add it as a feature and I'll merge it, don't want to merge testcode.

**Comment by cantbeatme** [comment]
How's that

**Comment by cantbeatme** [comment]
How's that

**Comment by certmemer** [comment]
You should as well fix indentation. `ImGui::Checkbox( charenc( "Bullet Trace" ), &Vars.Visuals.BulletTrace );
				ImGui::Checkbox(charenc("Dlights"), &Vars.Visuals.Dlights);` Looks a bit off.

**Comment by cantbeatme** [comment]
@EndScene.cpp the lines for bullet trace to Dlights are one after another, new lined already.

**Pull request merged**
