### PR TITLE
Update Hack

### PR DESCRIPTION
**Pull request by ClaudiuHKS**
Update Hack

Update EndScene.cpp - Fix Res. Change Fonts
Update DrawModelExecute.cpp - Fix No Flash
Update Draw.cpp - Improves Code Perf.
Update ConVar.h - Removed Unused Stuff
Update ConVar.cpp - Removed Unused Stuff

### CODE REVIEW

**Comment by bazzz1512** [comment]
Why are you removing Convars? Doesn't really make sense

**Comment by ClaudiuHKS** [comment]
They are not used. The Spoofed ones. They are/ were for SV_Cheats spoofing but TGF actually is not spoofing any ConVar.

**Comment by bazzz1512** [comment]
They aren't used, but this cheat should be used as a base for a cheat and not to cheat with it as is. It isn't used, but it's handy for people who want to spoof convars who are using this cheat as a base.

**Comment by ClaudiuHKS** [comment]
Didn't know that, sorry, cancelling it.

**Pull request closed without merging**
